version: '3'

services:
  roofis2:
    image: roofis2:1.0.0
    build: .
    volumes:
      - ./roofis2/public/config/config.json:/usr/share/nginx/html/config/config.json
    ports:
      - 8080:80
    env_file:
      - docker/roofis2/roofis2.env

  univis_api:
    image: michigg/univis_api
    ports:
      - 8888:80
    env_file:
      - docker/univis_api/univis_api.env

  roofis_api:
    image: michigg/roofis2_api
    ports:
      - 8181:80
    env_file:
      - docker/roofis_api/roofis_api.env

  lector_building_api:
    image: michigg/lector_building_api
    ports:
      - 9999:80

  redis:
    image: redis:5.0.6-alpine3.10
    command: --appendonly yes
    volumes:
      - ./data/redis:/data

